2023-02-16 04:25:53.627 | ERROR    | hcaptcha_challenger.core:challenge:551 - Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.77)
Stacktrace:
Backtrace:
	(No symbol) [0x005337D3]
	(No symbol) [0x004C8B81]
	(No symbol) [0x003CB36D]
	(No symbol) [0x003AE5DA]
	(No symbol) [0x0041F0CB]
	(No symbol) [0x00430A56]
	(No symbol) [0x0041B216]
	(No symbol) [0x003F0D97]
	(No symbol) [0x003F253D]
	GetHandleVerifier [0x007AABF2+2510930]
	GetHandleVerifier [0x007D8EC1+2700065]
	GetHandleVerifier [0x007DC86C+2714828]
	GetHandleVerifier [0x005E3480+645344]
	(No symbol) [0x004D0FD2]
	(No symbol) [0x004D6C68]
	(No symbol) [0x004D6D4B]
	(No symbol) [0x004E0D6B]
	BaseThreadInitThunk [0x76BA00F9+25]
	RtlGetAppContainerNamedObjectPath [0x776B7BBE+286]
	RtlGetAppContainerNamedObjectPath [0x776B7B8E+238]

Traceback (most recent call last):
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\hcaptha\hcaptcha-challenger\examples\demo_selenium.py", line 95, in <module>
    bytedance()
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\hcaptha\hcaptcha-challenger\examples\demo_selenium.py", line 85, in bytedance
    hit_challenge(ctx=driver, challenger=challenger)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\hcaptha\hcaptcha-challenger\examples\demo_selenium.py", line 48, in hit_challenge
    if (resp := challenger.anti_hcaptcha(ctx)) is None:
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 687, in anti_hcaptcha
    self.challenge(ctx, solution)
> File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 545, in challenge
    WebDriverWait(ctx, 15, ignored_exceptions=(ElementClickInterceptedException,)).until(
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 81, in until
    value = method(self._driver)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 312, in _predicate
    target = driver.find_element(*target)  # grab element at locator
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 855, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.77)
Stacktrace:
Backtrace:
	(No symbol) [0x005337D3]
	(No symbol) [0x004C8B81]
	(No symbol) [0x003CB36D]
	(No symbol) [0x003AE5DA]
	(No symbol) [0x0041F0CB]
	(No symbol) [0x00430A56]
	(No symbol) [0x0041B216]
	(No symbol) [0x003F0D97]
	(No symbol) [0x003F253D]
	GetHandleVerifier [0x007AABF2+2510930]
	GetHandleVerifier [0x007D8EC1+2700065]
	GetHandleVerifier [0x007DC86C+2714828]
	GetHandleVerifier [0x005E3480+645344]
	(No symbol) [0x004D0FD2]
	(No symbol) [0x004D6C68]
	(No symbol) [0x004D6D4B]
	(No symbol) [0x004E0D6B]
	BaseThreadInitThunk [0x76BA00F9+25]
	RtlGetAppContainerNamedObjectPath [0x776B7BBE+286]
	RtlGetAppContainerNamedObjectPath [0x776B7B8E+238]

2023-02-16 05:40:03.498 | ERROR    | hcaptcha_challenger.core:anti_hcaptcha:699 - Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.77)
Stacktrace:
Backtrace:
	(No symbol) [0x005337D3]
	(No symbol) [0x004C8B81]
	(No symbol) [0x003CB36D]
	(No symbol) [0x003AE5DA]
	(No symbol) [0x0041F0CB]
	(No symbol) [0x00430A56]
	(No symbol) [0x0041B216]
	(No symbol) [0x003F0D97]
	(No symbol) [0x003F253D]
	GetHandleVerifier [0x007AABF2+2510930]
	GetHandleVerifier [0x007D8EC1+2700065]
	GetHandleVerifier [0x007DC86C+2714828]
	GetHandleVerifier [0x005E3480+645344]
	(No symbol) [0x004D0FD2]
	(No symbol) [0x004D6C68]
	(No symbol) [0x004D6D4B]
	(No symbol) [0x004E0D6B]
	BaseThreadInitThunk [0x76BA00F9+25]
	RtlGetAppContainerNamedObjectPath [0x776B7BBE+286]
	RtlGetAppContainerNamedObjectPath [0x776B7B8E+238]

Traceback (most recent call last):
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\hcaptha\hcaptcha-challenger\examples\demo_selenium.py", line 95, in <module>
    bytedance()
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\hcaptha\hcaptcha-challenger\examples\demo_selenium.py", line 85, in bytedance
    hit_challenge(ctx=driver, challenger=challenger)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\hcaptha\hcaptcha-challenger\examples\demo_selenium.py", line 48, in hit_challenge
    if (resp := challenger.anti_hcaptcha(ctx)) is None:
> File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 690, in anti_hcaptcha
    result, _ = self.challenge_success(ctx)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 598, in challenge_success
    if is_flagged_flow():
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 587, in is_flagged_flow
    WebDriverWait(ctx, 1.2, poll_frequency=0.1).until(
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 81, in until
    value = method(self._driver)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 125, in _predicate
    return _element_if_visible(driver.find_element(*locator))
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 855, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.77)
Stacktrace:
Backtrace:
	(No symbol) [0x005337D3]
	(No symbol) [0x004C8B81]
	(No symbol) [0x003CB36D]
	(No symbol) [0x003AE5DA]
	(No symbol) [0x0041F0CB]
	(No symbol) [0x00430A56]
	(No symbol) [0x0041B216]
	(No symbol) [0x003F0D97]
	(No symbol) [0x003F253D]
	GetHandleVerifier [0x007AABF2+2510930]
	GetHandleVerifier [0x007D8EC1+2700065]
	GetHandleVerifier [0x007DC86C+2714828]
	GetHandleVerifier [0x005E3480+645344]
	(No symbol) [0x004D0FD2]
	(No symbol) [0x004D6C68]
	(No symbol) [0x004D6D4B]
	(No symbol) [0x004E0D6B]
	BaseThreadInitThunk [0x76BA00F9+25]
	RtlGetAppContainerNamedObjectPath [0x776B7BBE+286]
	RtlGetAppContainerNamedObjectPath [0x776B7B8E+238]

2023-02-18 03:22:42.829 | ERROR    | hcaptcha_challenger.core:tactical_retreat:382 - Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.77)
Stacktrace:
Backtrace:
	(No symbol) [0x005B37D3]
	(No symbol) [0x00548B81]
	(No symbol) [0x0044B36D]
	(No symbol) [0x0042E5DA]
	(No symbol) [0x0049F0CB]
	(No symbol) [0x004B0A56]
	(No symbol) [0x0049B216]
	(No symbol) [0x00470D97]
	(No symbol) [0x0047253D]
	GetHandleVerifier [0x0082ABF2+2510930]
	GetHandleVerifier [0x00858EC1+2700065]
	GetHandleVerifier [0x0085C86C+2714828]
	GetHandleVerifier [0x00663480+645344]
	(No symbol) [0x00550FD2]
	(No symbol) [0x00556C68]
	(No symbol) [0x00556D4B]
	(No symbol) [0x00560D6B]
	BaseThreadInitThunk [0x76BA00F9+25]
	RtlGetAppContainerNamedObjectPath [0x776B7BBE+286]
	RtlGetAppContainerNamedObjectPath [0x776B7B8E+238]

Traceback (most recent call last):
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\demo_selenium.py", line 86, in bytedance
    hit_challenge(ctx=driver, challenger=challenger)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\demo_selenium.py", line 48, in hit_challenge
    if (resp := challenger.anti_hcaptcha(ctx)) is None:
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 678, in anti_hcaptcha
    if drop := self.tactical_retreat(ctx) in [self.CHALLENGE_BACKCALL]:
> File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 377, in tactical_retreat
    challenge_container = ctx.find_element(By.XPATH, "//body[@class='no-selection']")
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 855, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.77)
Stacktrace:
Backtrace:
	(No symbol) [0x005B37D3]
	(No symbol) [0x00548B81]
	(No symbol) [0x0044B36D]
	(No symbol) [0x0042E5DA]
	(No symbol) [0x0049F0CB]
	(No symbol) [0x004B0A56]
	(No symbol) [0x0049B216]
	(No symbol) [0x00470D97]
	(No symbol) [0x0047253D]
	GetHandleVerifier [0x0082ABF2+2510930]
	GetHandleVerifier [0x00858EC1+2700065]
	GetHandleVerifier [0x0085C86C+2714828]
	GetHandleVerifier [0x00663480+645344]
	(No symbol) [0x00550FD2]
	(No symbol) [0x00556C68]
	(No symbol) [0x00556D4B]
	(No symbol) [0x00560D6B]
	BaseThreadInitThunk [0x76BA00F9+25]
	RtlGetAppContainerNamedObjectPath [0x776B7BBE+286]
	RtlGetAppContainerNamedObjectPath [0x776B7B8E+238]

2023-02-18 03:22:42.910 | ERROR    | hcaptcha_challenger.core:anti_hcaptcha:699 - Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.77)
Stacktrace:
Backtrace:
	(No symbol) [0x005B37D3]
	(No symbol) [0x00548B81]
	(No symbol) [0x0044B36D]
	(No symbol) [0x0042E5DA]
	(No symbol) [0x0049F0CB]
	(No symbol) [0x004B0A56]
	(No symbol) [0x0049B216]
	(No symbol) [0x00470D97]
	(No symbol) [0x0047253D]
	GetHandleVerifier [0x0082ABF2+2510930]
	GetHandleVerifier [0x00858EC1+2700065]
	GetHandleVerifier [0x0085C86C+2714828]
	GetHandleVerifier [0x00663480+645344]
	(No symbol) [0x00550FD2]
	(No symbol) [0x00556C68]
	(No symbol) [0x00556D4B]
	(No symbol) [0x00560D6B]
	BaseThreadInitThunk [0x76BA00F9+25]
	RtlGetAppContainerNamedObjectPath [0x776B7BBE+286]
	RtlGetAppContainerNamedObjectPath [0x776B7B8E+238]

Traceback (most recent call last):
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\demo_selenium.py", line 86, in bytedance
    hit_challenge(ctx=driver, challenger=challenger)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\demo_selenium.py", line 48, in hit_challenge
    if (resp := challenger.anti_hcaptcha(ctx)) is None:
> File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 678, in anti_hcaptcha
    if drop := self.tactical_retreat(ctx) in [self.CHALLENGE_BACKCALL]:
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 390, in tactical_retreat
    f"site_link={ctx.current_url} "
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 527, in current_url
    return self.execute(Command.GET_CURRENT_URL)['value']
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.77)
Stacktrace:
Backtrace:
	(No symbol) [0x005B37D3]
	(No symbol) [0x00548B81]
	(No symbol) [0x0044B36D]
	(No symbol) [0x0042E5DA]
	(No symbol) [0x0049F0CB]
	(No symbol) [0x004B0A56]
	(No symbol) [0x0049B216]
	(No symbol) [0x00470D97]
	(No symbol) [0x0047253D]
	GetHandleVerifier [0x0082ABF2+2510930]
	GetHandleVerifier [0x00858EC1+2700065]
	GetHandleVerifier [0x0085C86C+2714828]
	GetHandleVerifier [0x00663480+645344]
	(No symbol) [0x00550FD2]
	(No symbol) [0x00556C68]
	(No symbol) [0x00556D4B]
	(No symbol) [0x00560D6B]
	BaseThreadInitThunk [0x76BA00F9+25]
	RtlGetAppContainerNamedObjectPath [0x776B7BBE+286]
	RtlGetAppContainerNamedObjectPath [0x776B7B8E+238]

2023-02-18 03:30:08.773 | ERROR    | hcaptcha_challenger.core:tactical_retreat:382 - Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.77)
Stacktrace:
Backtrace:
	(No symbol) [0x004D37D3]
	(No symbol) [0x00468B81]
	(No symbol) [0x0036B36D]
	(No symbol) [0x0034E5DA]
	(No symbol) [0x003BF0CB]
	(No symbol) [0x003D0A56]
	(No symbol) [0x003BB216]
	(No symbol) [0x00390D97]
	(No symbol) [0x0039253D]
	GetHandleVerifier [0x0074ABF2+2510930]
	GetHandleVerifier [0x00778EC1+2700065]
	GetHandleVerifier [0x0077C86C+2714828]
	GetHandleVerifier [0x00583480+645344]
	(No symbol) [0x00470FD2]
	(No symbol) [0x00476C68]
	(No symbol) [0x00476D4B]
	(No symbol) [0x00480D6B]
	BaseThreadInitThunk [0x76BA00F9+25]
	RtlGetAppContainerNamedObjectPath [0x776B7BBE+286]
	RtlGetAppContainerNamedObjectPath [0x776B7B8E+238]

Traceback (most recent call last):
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\demo_selenium.py", line 85, in bytedance
    hit_challenge(ctx=driver, challenger=challenger)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\demo_selenium.py", line 48, in hit_challenge
    if (resp := challenger.anti_hcaptcha(ctx)) is None:
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 678, in anti_hcaptcha
    if drop := self.tactical_retreat(ctx) in [self.CHALLENGE_BACKCALL]:
> File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 377, in tactical_retreat
    challenge_container = ctx.find_element(By.XPATH, "//body[@class='no-selection']")
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 855, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.77)
Stacktrace:
Backtrace:
	(No symbol) [0x004D37D3]
	(No symbol) [0x00468B81]
	(No symbol) [0x0036B36D]
	(No symbol) [0x0034E5DA]
	(No symbol) [0x003BF0CB]
	(No symbol) [0x003D0A56]
	(No symbol) [0x003BB216]
	(No symbol) [0x00390D97]
	(No symbol) [0x0039253D]
	GetHandleVerifier [0x0074ABF2+2510930]
	GetHandleVerifier [0x00778EC1+2700065]
	GetHandleVerifier [0x0077C86C+2714828]
	GetHandleVerifier [0x00583480+645344]
	(No symbol) [0x00470FD2]
	(No symbol) [0x00476C68]
	(No symbol) [0x00476D4B]
	(No symbol) [0x00480D6B]
	BaseThreadInitThunk [0x76BA00F9+25]
	RtlGetAppContainerNamedObjectPath [0x776B7BBE+286]
	RtlGetAppContainerNamedObjectPath [0x776B7B8E+238]

2023-02-18 03:30:08.813 | ERROR    | hcaptcha_challenger.core:anti_hcaptcha:699 - Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.77)
Stacktrace:
Backtrace:
	(No symbol) [0x004D37D3]
	(No symbol) [0x00468B81]
	(No symbol) [0x0036B36D]
	(No symbol) [0x0034E5DA]
	(No symbol) [0x003BF0CB]
	(No symbol) [0x003D0A56]
	(No symbol) [0x003BB216]
	(No symbol) [0x00390D97]
	(No symbol) [0x0039253D]
	GetHandleVerifier [0x0074ABF2+2510930]
	GetHandleVerifier [0x00778EC1+2700065]
	GetHandleVerifier [0x0077C86C+2714828]
	GetHandleVerifier [0x00583480+645344]
	(No symbol) [0x00470FD2]
	(No symbol) [0x00476C68]
	(No symbol) [0x00476D4B]
	(No symbol) [0x00480D6B]
	BaseThreadInitThunk [0x76BA00F9+25]
	RtlGetAppContainerNamedObjectPath [0x776B7BBE+286]
	RtlGetAppContainerNamedObjectPath [0x776B7B8E+238]

Traceback (most recent call last):
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\demo_selenium.py", line 85, in bytedance
    hit_challenge(ctx=driver, challenger=challenger)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\demo_selenium.py", line 48, in hit_challenge
    if (resp := challenger.anti_hcaptcha(ctx)) is None:
> File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 678, in anti_hcaptcha
    if drop := self.tactical_retreat(ctx) in [self.CHALLENGE_BACKCALL]:
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 390, in tactical_retreat
    f"site_link={ctx.current_url} "
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\undetected_chromedriver\__init__.py", line 433, in __getattribute__
    return super().__getattribute__(item)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 527, in current_url
    return self.execute(Command.GET_CURRENT_URL)['value']
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.77)
Stacktrace:
Backtrace:
	(No symbol) [0x004D37D3]
	(No symbol) [0x00468B81]
	(No symbol) [0x0036B36D]
	(No symbol) [0x0034E5DA]
	(No symbol) [0x003BF0CB]
	(No symbol) [0x003D0A56]
	(No symbol) [0x003BB216]
	(No symbol) [0x00390D97]
	(No symbol) [0x0039253D]
	GetHandleVerifier [0x0074ABF2+2510930]
	GetHandleVerifier [0x00778EC1+2700065]
	GetHandleVerifier [0x0077C86C+2714828]
	GetHandleVerifier [0x00583480+645344]
	(No symbol) [0x00470FD2]
	(No symbol) [0x00476C68]
	(No symbol) [0x00476D4B]
	(No symbol) [0x00480D6B]
	BaseThreadInitThunk [0x76BA00F9+25]
	RtlGetAppContainerNamedObjectPath [0x776B7BBE+286]
	RtlGetAppContainerNamedObjectPath [0x776B7B8E+238]

2023-02-18 03:45:23.318 | ERROR    | hcaptcha_challenger.core:anti_hcaptcha:699 - Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.77)
Stacktrace:
Backtrace:
	(No symbol) [0x005E37D3]
	(No symbol) [0x00578B81]
	(No symbol) [0x0047B36D]
	(No symbol) [0x0045E5DA]
	(No symbol) [0x004CF0CB]
	(No symbol) [0x004E0A56]
	(No symbol) [0x004CB216]
	(No symbol) [0x004A0D97]
	(No symbol) [0x004A253D]
	GetHandleVerifier [0x0085ABF2+2510930]
	GetHandleVerifier [0x00888EC1+2700065]
	GetHandleVerifier [0x0088C86C+2714828]
	GetHandleVerifier [0x00693480+645344]
	(No symbol) [0x00580FD2]
	(No symbol) [0x00586C68]
	(No symbol) [0x00586D4B]
	(No symbol) [0x00590D6B]
	BaseThreadInitThunk [0x76BA00F9+25]
	RtlGetAppContainerNamedObjectPath [0x776B7BBE+286]
	RtlGetAppContainerNamedObjectPath [0x776B7B8E+238]

Traceback (most recent call last):
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\demo_selenium.py", line 88, in bytedance
    hit_challenge(ctx=driver, challenger=challenger)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\demo_selenium.py", line 50, in hit_challenge
    if (resp := challenger.anti_hcaptcha(ctx)) is None:
> File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 662, in anti_hcaptcha
    if drop := self.get_label(ctx) in [self.CHALLENGE_BACKCALL]:
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 337, in get_label
    ).until(EC.presence_of_element_located((By.XPATH, "//h2[@class='prompt-text']")))
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 81, in until
    value = method(self._driver)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 64, in _predicate
    return driver.find_element(*locator)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 855, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.77)
Stacktrace:
Backtrace:
	(No symbol) [0x005E37D3]
	(No symbol) [0x00578B81]
	(No symbol) [0x0047B36D]
	(No symbol) [0x0045E5DA]
	(No symbol) [0x004CF0CB]
	(No symbol) [0x004E0A56]
	(No symbol) [0x004CB216]
	(No symbol) [0x004A0D97]
	(No symbol) [0x004A253D]
	GetHandleVerifier [0x0085ABF2+2510930]
	GetHandleVerifier [0x00888EC1+2700065]
	GetHandleVerifier [0x0088C86C+2714828]
	GetHandleVerifier [0x00693480+645344]
	(No symbol) [0x00580FD2]
	(No symbol) [0x00586C68]
	(No symbol) [0x00586D4B]
	(No symbol) [0x00590D6B]
	BaseThreadInitThunk [0x76BA00F9+25]
	RtlGetAppContainerNamedObjectPath [0x776B7BBE+286]
	RtlGetAppContainerNamedObjectPath [0x776B7B8E+238]

2023-02-18 18:18:19.943 | ERROR    | hcaptcha_challenger.core:captcha_screenshot:299 - Message: stale element reference: element is not attached to the page document
  (Session info: chrome=110.0.5481.77)
Stacktrace:
Backtrace:
	(No symbol) [0x010137D3]
	(No symbol) [0x00FA8B81]
	(No symbol) [0x00EAB36D]
	(No symbol) [0x00EAE0FB]
	(No symbol) [0x00EADFD0]
	(No symbol) [0x00EAE250]
	(No symbol) [0x00EDF8D5]
	(No symbol) [0x00EE1A7B]
	(No symbol) [0x00EDADCB]
	(No symbol) [0x00EFB41C]
	(No symbol) [0x00ED2B96]
	(No symbol) [0x00EFB774]
	(No symbol) [0x00F11215]
	(No symbol) [0x00EFB216]
	(No symbol) [0x00ED0D97]
	(No symbol) [0x00ED253D]
	GetHandleVerifier [0x0128ABF2+2510930]
	GetHandleVerifier [0x012B8EC1+2700065]
	GetHandleVerifier [0x012BC86C+2714828]
	GetHandleVerifier [0x010C3480+645344]
	(No symbol) [0x00FB0FD2]
	(No symbol) [0x00FB6C68]
	(No symbol) [0x00FB6D4B]
	(No symbol) [0x00FC0D6B]
	BaseThreadInitThunk [0x76BA00F9+25]
	RtlGetAppContainerNamedObjectPath [0x776B7BBE+286]
	RtlGetAppContainerNamedObjectPath [0x776B7B8E+238]

Traceback (most recent call last):
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\demo_selenium.py", line 86, in bytedance
    hit_challenge(ctx=driver, challenger=challenger)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\demo_selenium.py", line 48, in hit_challenge
    if (resp := challenger.anti_hcaptcha(ctx)) is None:
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 678, in anti_hcaptcha
    if drop := self.tactical_retreat(ctx) in [self.CHALLENGE_BACKCALL]:
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 378, in tactical_retreat
    self.path_screenshot = self.captcha_screenshot(challenge_container)
> File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 295, in captcha_screenshot
    ctx.screenshot(_out_path)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webelement.py", line 348, in screenshot
    png = self.screenshot_as_png
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webelement.py", line 328, in screenshot_as_png
    return b64decode(self.screenshot_as_base64.encode('ascii'))
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webelement.py", line 316, in screenshot_as_base64
    return self._execute(Command.ELEMENT_SCREENSHOT)['value']
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webelement.py", line 396, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=110.0.5481.77)
Stacktrace:
Backtrace:
	(No symbol) [0x010137D3]
	(No symbol) [0x00FA8B81]
	(No symbol) [0x00EAB36D]
	(No symbol) [0x00EAE0FB]
	(No symbol) [0x00EADFD0]
	(No symbol) [0x00EAE250]
	(No symbol) [0x00EDF8D5]
	(No symbol) [0x00EE1A7B]
	(No symbol) [0x00EDADCB]
	(No symbol) [0x00EFB41C]
	(No symbol) [0x00ED2B96]
	(No symbol) [0x00EFB774]
	(No symbol) [0x00F11215]
	(No symbol) [0x00EFB216]
	(No symbol) [0x00ED0D97]
	(No symbol) [0x00ED253D]
	GetHandleVerifier [0x0128ABF2+2510930]
	GetHandleVerifier [0x012B8EC1+2700065]
	GetHandleVerifier [0x012BC86C+2714828]
	GetHandleVerifier [0x010C3480+645344]
	(No symbol) [0x00FB0FD2]
	(No symbol) [0x00FB6C68]
	(No symbol) [0x00FB6D4B]
	(No symbol) [0x00FC0D6B]
	BaseThreadInitThunk [0x76BA00F9+25]
	RtlGetAppContainerNamedObjectPath [0x776B7BBE+286]
	RtlGetAppContainerNamedObjectPath [0x776B7B8E+238]

2023-02-18 18:18:24.431 | ERROR    | hcaptcha_challenger.core:anti_hcaptcha:699 - Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.77)
Stacktrace:
Backtrace:
	(No symbol) [0x010137D3]
	(No symbol) [0x00FA8B81]
	(No symbol) [0x00EAB36D]
	(No symbol) [0x00E8E5DA]
	(No symbol) [0x00EFF0CB]
	(No symbol) [0x00F10A56]
	(No symbol) [0x00EFB216]
	(No symbol) [0x00ED0D97]
	(No symbol) [0x00ED253D]
	GetHandleVerifier [0x0128ABF2+2510930]
	GetHandleVerifier [0x012B8EC1+2700065]
	GetHandleVerifier [0x012BC86C+2714828]
	GetHandleVerifier [0x010C3480+645344]
	(No symbol) [0x00FB0FD2]
	(No symbol) [0x00FB6C68]
	(No symbol) [0x00FB6D4B]
	(No symbol) [0x00FC0D6B]
	BaseThreadInitThunk [0x76BA00F9+25]
	RtlGetAppContainerNamedObjectPath [0x776B7BBE+286]
	RtlGetAppContainerNamedObjectPath [0x776B7B8E+238]

Traceback (most recent call last):
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\demo_selenium.py", line 86, in bytedance
    hit_challenge(ctx=driver, challenger=challenger)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\demo_selenium.py", line 48, in hit_challenge
    if (resp := challenger.anti_hcaptcha(ctx)) is None:
> File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 667, in anti_hcaptcha
    if drop := self.mark_samples(ctx) in [
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 432, in mark_samples
    samples = ctx.find_elements(By.XPATH, "//div[@class='task-image']")
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_elements
    return self.execute(Command.FIND_ELEMENTS, {
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.77)
Stacktrace:
Backtrace:
	(No symbol) [0x010137D3]
	(No symbol) [0x00FA8B81]
	(No symbol) [0x00EAB36D]
	(No symbol) [0x00E8E5DA]
	(No symbol) [0x00EFF0CB]
	(No symbol) [0x00F10A56]
	(No symbol) [0x00EFB216]
	(No symbol) [0x00ED0D97]
	(No symbol) [0x00ED253D]
	GetHandleVerifier [0x0128ABF2+2510930]
	GetHandleVerifier [0x012B8EC1+2700065]
	GetHandleVerifier [0x012BC86C+2714828]
	GetHandleVerifier [0x010C3480+645344]
	(No symbol) [0x00FB0FD2]
	(No symbol) [0x00FB6C68]
	(No symbol) [0x00FB6D4B]
	(No symbol) [0x00FC0D6B]
	BaseThreadInitThunk [0x76BA00F9+25]
	RtlGetAppContainerNamedObjectPath [0x776B7BBE+286]
	RtlGetAppContainerNamedObjectPath [0x776B7B8E+238]

2023-02-18 19:19:08.373 | ERROR    | hcaptcha_challenger.core:anti_hcaptcha:699 - Message: stale element reference: element is not attached to the page document
  (Session info: chrome=110.0.5481.77)
Stacktrace:
Backtrace:
	(No symbol) [0x009F37D3]
	(No symbol) [0x00988B81]
	(No symbol) [0x0088B36D]
	(No symbol) [0x0088E0FB]
	(No symbol) [0x0088DFD0]
	(No symbol) [0x0088EA35]
	(No symbol) [0x008F209F]
	(No symbol) [0x008DB41C]
	(No symbol) [0x008F1215]
	(No symbol) [0x008DB216]
	(No symbol) [0x008B0D97]
	(No symbol) [0x008B253D]
	GetHandleVerifier [0x00C6ABF2+2510930]
	GetHandleVerifier [0x00C98EC1+2700065]
	GetHandleVerifier [0x00C9C86C+2714828]
	GetHandleVerifier [0x00AA3480+645344]
	(No symbol) [0x00990FD2]
	(No symbol) [0x00996C68]
	(No symbol) [0x00996D4B]
	(No symbol) [0x009A0D6B]
	BaseThreadInitThunk [0x76BA00F9+25]
	RtlGetAppContainerNamedObjectPath [0x776B7BBE+286]
	RtlGetAppContainerNamedObjectPath [0x776B7B8E+238]

Traceback (most recent call last):
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\demo_selenium.py", line 90, in bytedance
    hit_challenge(ctx=driver, challenger=challenger)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\demo_selenium.py", line 48, in hit_challenge
    if (resp := challenger.anti_hcaptcha(ctx)) is None:
> File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 667, in anti_hcaptcha
    if drop := self.mark_samples(ctx) in [
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 434, in mark_samples
    alias = sample.get_attribute("aria-label")
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webelement.py", line 172, in get_attribute
    attribute_value = self.parent.execute_script(
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 491, in execute_script
    return self.execute(command, {
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=110.0.5481.77)
Stacktrace:
Backtrace:
	(No symbol) [0x009F37D3]
	(No symbol) [0x00988B81]
	(No symbol) [0x0088B36D]
	(No symbol) [0x0088E0FB]
	(No symbol) [0x0088DFD0]
	(No symbol) [0x0088EA35]
	(No symbol) [0x008F209F]
	(No symbol) [0x008DB41C]
	(No symbol) [0x008F1215]
	(No symbol) [0x008DB216]
	(No symbol) [0x008B0D97]
	(No symbol) [0x008B253D]
	GetHandleVerifier [0x00C6ABF2+2510930]
	GetHandleVerifier [0x00C98EC1+2700065]
	GetHandleVerifier [0x00C9C86C+2714828]
	GetHandleVerifier [0x00AA3480+645344]
	(No symbol) [0x00990FD2]
	(No symbol) [0x00996C68]
	(No symbol) [0x00996D4B]
	(No symbol) [0x009A0D6B]
	BaseThreadInitThunk [0x76BA00F9+25]
	RtlGetAppContainerNamedObjectPath [0x776B7BBE+286]
	RtlGetAppContainerNamedObjectPath [0x776B7B8E+238]

2023-02-18 19:19:09.427 | ERROR    | hcaptcha_challenger.core:anti_hcaptcha:699 - Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.77)
Stacktrace:
Backtrace:
	(No symbol) [0x009F37D3]
	(No symbol) [0x00988B81]
	(No symbol) [0x0088B36D]
	(No symbol) [0x0086E5DA]
	(No symbol) [0x008DF0CB]
	(No symbol) [0x008F0A56]
	(No symbol) [0x008DB216]
	(No symbol) [0x008B0D97]
	(No symbol) [0x008B253D]
	GetHandleVerifier [0x00C6ABF2+2510930]
	GetHandleVerifier [0x00C98EC1+2700065]
	GetHandleVerifier [0x00C9C86C+2714828]
	GetHandleVerifier [0x00AA3480+645344]
	(No symbol) [0x00990FD2]
	(No symbol) [0x00996C68]
	(No symbol) [0x00996D4B]
	(No symbol) [0x009A0D6B]
	BaseThreadInitThunk [0x76BA00F9+25]
	RtlGetAppContainerNamedObjectPath [0x776B7BBE+286]
	RtlGetAppContainerNamedObjectPath [0x776B7B8E+238]

Traceback (most recent call last):
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\demo_selenium.py", line 90, in bytedance
    hit_challenge(ctx=driver, challenger=challenger)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\demo_selenium.py", line 48, in hit_challenge
    if (resp := challenger.anti_hcaptcha(ctx)) is None:
> File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 659, in anti_hcaptcha
    self.switch_to_challenge_frame(ctx)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 320, in switch_to_challenge_frame
    WebDriverWait(ctx, 15, ignored_exceptions=(ElementNotVisibleException,)).until(
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 81, in until
    value = method(self._driver)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 256, in _predicate
    driver.switch_to.frame(driver.find_element(*locator))
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 855, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.77)
Stacktrace:
Backtrace:
	(No symbol) [0x009F37D3]
	(No symbol) [0x00988B81]
	(No symbol) [0x0088B36D]
	(No symbol) [0x0086E5DA]
	(No symbol) [0x008DF0CB]
	(No symbol) [0x008F0A56]
	(No symbol) [0x008DB216]
	(No symbol) [0x008B0D97]
	(No symbol) [0x008B253D]
	GetHandleVerifier [0x00C6ABF2+2510930]
	GetHandleVerifier [0x00C98EC1+2700065]
	GetHandleVerifier [0x00C9C86C+2714828]
	GetHandleVerifier [0x00AA3480+645344]
	(No symbol) [0x00990FD2]
	(No symbol) [0x00996C68]
	(No symbol) [0x00996D4B]
	(No symbol) [0x009A0D6B]
	BaseThreadInitThunk [0x76BA00F9+25]
	RtlGetAppContainerNamedObjectPath [0x776B7BBE+286]
	RtlGetAppContainerNamedObjectPath [0x776B7B8E+238]

2023-02-18 20:04:54.111 | ERROR    | hcaptcha_challenger.core:tactical_retreat:382 - Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.77)
Stacktrace:
Backtrace:
	(No symbol) [0x011737D3]
	(No symbol) [0x01108B81]
	(No symbol) [0x0100B36D]
	(No symbol) [0x00FEE5DA]
	(No symbol) [0x0105F0CB]
	(No symbol) [0x01070A56]
	(No symbol) [0x0105B216]
	(No symbol) [0x01030D97]
	(No symbol) [0x0103253D]
	GetHandleVerifier [0x013EABF2+2510930]
	GetHandleVerifier [0x01418EC1+2700065]
	GetHandleVerifier [0x0141C86C+2714828]
	GetHandleVerifier [0x01223480+645344]
	(No symbol) [0x01110FD2]
	(No symbol) [0x01116C68]
	(No symbol) [0x01116D4B]
	(No symbol) [0x01120D6B]
	BaseThreadInitThunk [0x76BA00F9+25]
	RtlGetAppContainerNamedObjectPath [0x776B7BBE+286]
	RtlGetAppContainerNamedObjectPath [0x776B7B8E+238]

Traceback (most recent call last):
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\demo_selenium.py", line 96, in bytedance
    hit_challenge(ctx=driver, challenger=challenger)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\demo_selenium.py", line 50, in hit_challenge
    if (resp := challenger.anti_hcaptcha(ctx)) is None:
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 678, in anti_hcaptcha
    if drop := self.tactical_retreat(ctx) in [self.CHALLENGE_BACKCALL]:
> File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 377, in tactical_retreat
    challenge_container = ctx.find_element(By.XPATH, "//body[@class='no-selection']")
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 855, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.77)
Stacktrace:
Backtrace:
	(No symbol) [0x011737D3]
	(No symbol) [0x01108B81]
	(No symbol) [0x0100B36D]
	(No symbol) [0x00FEE5DA]
	(No symbol) [0x0105F0CB]
	(No symbol) [0x01070A56]
	(No symbol) [0x0105B216]
	(No symbol) [0x01030D97]
	(No symbol) [0x0103253D]
	GetHandleVerifier [0x013EABF2+2510930]
	GetHandleVerifier [0x01418EC1+2700065]
	GetHandleVerifier [0x0141C86C+2714828]
	GetHandleVerifier [0x01223480+645344]
	(No symbol) [0x01110FD2]
	(No symbol) [0x01116C68]
	(No symbol) [0x01116D4B]
	(No symbol) [0x01120D6B]
	BaseThreadInitThunk [0x76BA00F9+25]
	RtlGetAppContainerNamedObjectPath [0x776B7BBE+286]
	RtlGetAppContainerNamedObjectPath [0x776B7B8E+238]

2023-02-18 20:04:54.163 | ERROR    | hcaptcha_challenger.core:anti_hcaptcha:699 - Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.77)
Stacktrace:
Backtrace:
	(No symbol) [0x011737D3]
	(No symbol) [0x01108B81]
	(No symbol) [0x0100B36D]
	(No symbol) [0x00FEE5DA]
	(No symbol) [0x0105F0CB]
	(No symbol) [0x01070A56]
	(No symbol) [0x0105B216]
	(No symbol) [0x01030D97]
	(No symbol) [0x0103253D]
	GetHandleVerifier [0x013EABF2+2510930]
	GetHandleVerifier [0x01418EC1+2700065]
	GetHandleVerifier [0x0141C86C+2714828]
	GetHandleVerifier [0x01223480+645344]
	(No symbol) [0x01110FD2]
	(No symbol) [0x01116C68]
	(No symbol) [0x01116D4B]
	(No symbol) [0x01120D6B]
	BaseThreadInitThunk [0x76BA00F9+25]
	RtlGetAppContainerNamedObjectPath [0x776B7BBE+286]
	RtlGetAppContainerNamedObjectPath [0x776B7B8E+238]

Traceback (most recent call last):
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\demo_selenium.py", line 96, in bytedance
    hit_challenge(ctx=driver, challenger=challenger)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\demo_selenium.py", line 50, in hit_challenge
    if (resp := challenger.anti_hcaptcha(ctx)) is None:
> File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 678, in anti_hcaptcha
    if drop := self.tactical_retreat(ctx) in [self.CHALLENGE_BACKCALL]:
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 390, in tactical_retreat
    f"site_link={ctx.current_url} "
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\undetected_chromedriver\__init__.py", line 433, in __getattribute__
    return super().__getattribute__(item)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 527, in current_url
    return self.execute(Command.GET_CURRENT_URL)['value']
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.77)
Stacktrace:
Backtrace:
	(No symbol) [0x011737D3]
	(No symbol) [0x01108B81]
	(No symbol) [0x0100B36D]
	(No symbol) [0x00FEE5DA]
	(No symbol) [0x0105F0CB]
	(No symbol) [0x01070A56]
	(No symbol) [0x0105B216]
	(No symbol) [0x01030D97]
	(No symbol) [0x0103253D]
	GetHandleVerifier [0x013EABF2+2510930]
	GetHandleVerifier [0x01418EC1+2700065]
	GetHandleVerifier [0x0141C86C+2714828]
	GetHandleVerifier [0x01223480+645344]
	(No symbol) [0x01110FD2]
	(No symbol) [0x01116C68]
	(No symbol) [0x01116D4B]
	(No symbol) [0x01120D6B]
	BaseThreadInitThunk [0x76BA00F9+25]
	RtlGetAppContainerNamedObjectPath [0x776B7BBE+286]
	RtlGetAppContainerNamedObjectPath [0x776B7B8E+238]

2023-02-19 03:04:36.376 | ERROR    | hcaptcha_challenger.core:anti_hcaptcha:699 - Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.77)
Stacktrace:
Backtrace:
	(No symbol) [0x00B437D3]
	(No symbol) [0x00AD8B81]
	(No symbol) [0x009DB36D]
	(No symbol) [0x009BE5DA]
	(No symbol) [0x00A2F0CB]
	(No symbol) [0x00A40A56]
	(No symbol) [0x00A2B216]
	(No symbol) [0x00A00D97]
	(No symbol) [0x00A0253D]
	GetHandleVerifier [0x00DBABF2+2510930]
	GetHandleVerifier [0x00DE8EC1+2700065]
	GetHandleVerifier [0x00DEC86C+2714828]
	GetHandleVerifier [0x00BF3480+645344]
	(No symbol) [0x00AE0FD2]
	(No symbol) [0x00AE6C68]
	(No symbol) [0x00AE6D4B]
	(No symbol) [0x00AF0D6B]
	BaseThreadInitThunk [0x76BA00F9+25]
	RtlGetAppContainerNamedObjectPath [0x776B7BBE+286]
	RtlGetAppContainerNamedObjectPath [0x776B7B8E+238]

Traceback (most recent call last):
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\start.py", line 109, in <module>
    bytedance()
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\start.py", line 99, in bytedance
    hit_challenge(ctx=driver, challenger=challenger)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\start.py", line 50, in hit_challenge
    if (resp := challenger.anti_hcaptcha(ctx)) is None:
> File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 667, in anti_hcaptcha
    if drop := self.mark_samples(ctx) in [
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 432, in mark_samples
    samples = ctx.find_elements(By.XPATH, "//div[@class='task-image']")
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_elements
    return self.execute(Command.FIND_ELEMENTS, {
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.77)
Stacktrace:
Backtrace:
	(No symbol) [0x00B437D3]
	(No symbol) [0x00AD8B81]
	(No symbol) [0x009DB36D]
	(No symbol) [0x009BE5DA]
	(No symbol) [0x00A2F0CB]
	(No symbol) [0x00A40A56]
	(No symbol) [0x00A2B216]
	(No symbol) [0x00A00D97]
	(No symbol) [0x00A0253D]
	GetHandleVerifier [0x00DBABF2+2510930]
	GetHandleVerifier [0x00DE8EC1+2700065]
	GetHandleVerifier [0x00DEC86C+2714828]
	GetHandleVerifier [0x00BF3480+645344]
	(No symbol) [0x00AE0FD2]
	(No symbol) [0x00AE6C68]
	(No symbol) [0x00AE6D4B]
	(No symbol) [0x00AF0D6B]
	BaseThreadInitThunk [0x76BA00F9+25]
	RtlGetAppContainerNamedObjectPath [0x776B7BBE+286]
	RtlGetAppContainerNamedObjectPath [0x776B7B8E+238]

2023-02-19 03:55:55.156 | ERROR    | hcaptcha_challenger.core:anti_hcaptcha:699 - Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.77)
Stacktrace:
Backtrace:
	(No symbol) [0x006E37D3]
	(No symbol) [0x00678B81]
	(No symbol) [0x0057B36D]
	(No symbol) [0x0055E5DA]
	(No symbol) [0x005CF0CB]
	(No symbol) [0x005E0A56]
	(No symbol) [0x005CB216]
	(No symbol) [0x005A0D97]
	(No symbol) [0x005A253D]
	GetHandleVerifier [0x0095ABF2+2510930]
	GetHandleVerifier [0x00988EC1+2700065]
	GetHandleVerifier [0x0098C86C+2714828]
	GetHandleVerifier [0x00793480+645344]
	(No symbol) [0x00680FD2]
	(No symbol) [0x00686C68]
	(No symbol) [0x00686D4B]
	(No symbol) [0x00690D6B]
	BaseThreadInitThunk [0x76BA00F9+25]
	RtlGetAppContainerNamedObjectPath [0x776B7BBE+286]
	RtlGetAppContainerNamedObjectPath [0x776B7B8E+238]

Traceback (most recent call last):
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\start.py", line 122, in <module>
    bytedance()
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\start.py", line 97, in bytedance
    hit_challenge(ctx=driver, challenger=challenger)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\start.py", line 50, in hit_challenge
    if (resp := challenger.anti_hcaptcha(ctx)) is None:
> File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 667, in anti_hcaptcha
    if drop := self.mark_samples(ctx) in [
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 432, in mark_samples
    samples = ctx.find_elements(By.XPATH, "//div[@class='task-image']")
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_elements
    return self.execute(Command.FIND_ELEMENTS, {
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.77)
Stacktrace:
Backtrace:
	(No symbol) [0x006E37D3]
	(No symbol) [0x00678B81]
	(No symbol) [0x0057B36D]
	(No symbol) [0x0055E5DA]
	(No symbol) [0x005CF0CB]
	(No symbol) [0x005E0A56]
	(No symbol) [0x005CB216]
	(No symbol) [0x005A0D97]
	(No symbol) [0x005A253D]
	GetHandleVerifier [0x0095ABF2+2510930]
	GetHandleVerifier [0x00988EC1+2700065]
	GetHandleVerifier [0x0098C86C+2714828]
	GetHandleVerifier [0x00793480+645344]
	(No symbol) [0x00680FD2]
	(No symbol) [0x00686C68]
	(No symbol) [0x00686D4B]
	(No symbol) [0x00690D6B]
	BaseThreadInitThunk [0x76BA00F9+25]
	RtlGetAppContainerNamedObjectPath [0x776B7BBE+286]
	RtlGetAppContainerNamedObjectPath [0x776B7B8E+238]

2023-02-20 00:39:33.467 | ERROR    | hcaptcha_challenger.core:captcha_screenshot:299 - Message: stale element reference: element is not attached to the page document
  (Session info: chrome=110.0.5481.104)
Stacktrace:
Backtrace:
	(No symbol) [0x009637D3]
	(No symbol) [0x008F8B81]
	(No symbol) [0x007FB36D]
	(No symbol) [0x007FE0FB]
	(No symbol) [0x007FDFD0]
	(No symbol) [0x007FE250]
	(No symbol) [0x0082F8D5]
	(No symbol) [0x00831A7B]
	(No symbol) [0x0082ADCB]
	(No symbol) [0x0084B41C]
	(No symbol) [0x00822B96]
	(No symbol) [0x0084B774]
	(No symbol) [0x00861215]
	(No symbol) [0x0084B216]
	(No symbol) [0x00820D97]
	(No symbol) [0x0082253D]
	GetHandleVerifier [0x00BDABF2+2510930]
	GetHandleVerifier [0x00C08EC1+2700065]
	GetHandleVerifier [0x00C0C86C+2714828]
	GetHandleVerifier [0x00A13480+645344]
	(No symbol) [0x00900FD2]
	(No symbol) [0x00906C68]
	(No symbol) [0x00906D4B]
	(No symbol) [0x00910D6B]
	BaseThreadInitThunk [0x75C000F9+25]
	RtlGetAppContainerNamedObjectPath [0x77167BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77167B8E+238]

Traceback (most recent call last):
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\start.py", line 121, in <module>
    bytedance()
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\start.py", line 109, in bytedance
    hit_challenge(ctx=driver, challenger=challenger)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\start.py", line 50, in hit_challenge
    if (resp := challenger.anti_hcaptcha(ctx)) is None:
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 678, in anti_hcaptcha
    if drop := self.tactical_retreat(ctx) in [self.CHALLENGE_BACKCALL]:
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 378, in tactical_retreat
    self.path_screenshot = self.captcha_screenshot(challenge_container)
> File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 295, in captcha_screenshot
    ctx.screenshot(_out_path)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webelement.py", line 348, in screenshot
    png = self.screenshot_as_png
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webelement.py", line 328, in screenshot_as_png
    return b64decode(self.screenshot_as_base64.encode('ascii'))
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webelement.py", line 316, in screenshot_as_base64
    return self._execute(Command.ELEMENT_SCREENSHOT)['value']
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webelement.py", line 396, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=110.0.5481.104)
Stacktrace:
Backtrace:
	(No symbol) [0x009637D3]
	(No symbol) [0x008F8B81]
	(No symbol) [0x007FB36D]
	(No symbol) [0x007FE0FB]
	(No symbol) [0x007FDFD0]
	(No symbol) [0x007FE250]
	(No symbol) [0x0082F8D5]
	(No symbol) [0x00831A7B]
	(No symbol) [0x0082ADCB]
	(No symbol) [0x0084B41C]
	(No symbol) [0x00822B96]
	(No symbol) [0x0084B774]
	(No symbol) [0x00861215]
	(No symbol) [0x0084B216]
	(No symbol) [0x00820D97]
	(No symbol) [0x0082253D]
	GetHandleVerifier [0x00BDABF2+2510930]
	GetHandleVerifier [0x00C08EC1+2700065]
	GetHandleVerifier [0x00C0C86C+2714828]
	GetHandleVerifier [0x00A13480+645344]
	(No symbol) [0x00900FD2]
	(No symbol) [0x00906C68]
	(No symbol) [0x00906D4B]
	(No symbol) [0x00910D6B]
	BaseThreadInitThunk [0x75C000F9+25]
	RtlGetAppContainerNamedObjectPath [0x77167BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77167B8E+238]

2023-02-20 00:40:14.720 | ERROR    | hcaptcha_challenger.core:tactical_retreat:382 - Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.104)
Stacktrace:
Backtrace:
	(No symbol) [0x009637D3]
	(No symbol) [0x008F8B81]
	(No symbol) [0x007FB36D]
	(No symbol) [0x007DE5DA]
	(No symbol) [0x0084F0CB]
	(No symbol) [0x00860A56]
	(No symbol) [0x0084B216]
	(No symbol) [0x00820D97]
	(No symbol) [0x0082253D]
	GetHandleVerifier [0x00BDABF2+2510930]
	GetHandleVerifier [0x00C08EC1+2700065]
	GetHandleVerifier [0x00C0C86C+2714828]
	GetHandleVerifier [0x00A13480+645344]
	(No symbol) [0x00900FD2]
	(No symbol) [0x00906C68]
	(No symbol) [0x00906D4B]
	(No symbol) [0x00910D6B]
	BaseThreadInitThunk [0x75C000F9+25]
	RtlGetAppContainerNamedObjectPath [0x77167BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77167B8E+238]

Traceback (most recent call last):
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\start.py", line 121, in <module>
    bytedance()
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\start.py", line 109, in bytedance
    hit_challenge(ctx=driver, challenger=challenger)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\start.py", line 50, in hit_challenge
    if (resp := challenger.anti_hcaptcha(ctx)) is None:
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 678, in anti_hcaptcha
    if drop := self.tactical_retreat(ctx) in [self.CHALLENGE_BACKCALL]:
> File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 377, in tactical_retreat
    challenge_container = ctx.find_element(By.XPATH, "//body[@class='no-selection']")
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 855, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.104)
Stacktrace:
Backtrace:
	(No symbol) [0x009637D3]
	(No symbol) [0x008F8B81]
	(No symbol) [0x007FB36D]
	(No symbol) [0x007DE5DA]
	(No symbol) [0x0084F0CB]
	(No symbol) [0x00860A56]
	(No symbol) [0x0084B216]
	(No symbol) [0x00820D97]
	(No symbol) [0x0082253D]
	GetHandleVerifier [0x00BDABF2+2510930]
	GetHandleVerifier [0x00C08EC1+2700065]
	GetHandleVerifier [0x00C0C86C+2714828]
	GetHandleVerifier [0x00A13480+645344]
	(No symbol) [0x00900FD2]
	(No symbol) [0x00906C68]
	(No symbol) [0x00906D4B]
	(No symbol) [0x00910D6B]
	BaseThreadInitThunk [0x75C000F9+25]
	RtlGetAppContainerNamedObjectPath [0x77167BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77167B8E+238]

2023-02-20 00:40:14.747 | ERROR    | hcaptcha_challenger.core:anti_hcaptcha:699 - Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.104)
Stacktrace:
Backtrace:
	(No symbol) [0x009637D3]
	(No symbol) [0x008F8B81]
	(No symbol) [0x007FB36D]
	(No symbol) [0x007DE5DA]
	(No symbol) [0x0084F0CB]
	(No symbol) [0x00860A56]
	(No symbol) [0x0084B216]
	(No symbol) [0x00820D97]
	(No symbol) [0x0082253D]
	GetHandleVerifier [0x00BDABF2+2510930]
	GetHandleVerifier [0x00C08EC1+2700065]
	GetHandleVerifier [0x00C0C86C+2714828]
	GetHandleVerifier [0x00A13480+645344]
	(No symbol) [0x00900FD2]
	(No symbol) [0x00906C68]
	(No symbol) [0x00906D4B]
	(No symbol) [0x00910D6B]
	BaseThreadInitThunk [0x75C000F9+25]
	RtlGetAppContainerNamedObjectPath [0x77167BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77167B8E+238]

Traceback (most recent call last):
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\start.py", line 121, in <module>
    bytedance()
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\start.py", line 109, in bytedance
    hit_challenge(ctx=driver, challenger=challenger)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\start.py", line 50, in hit_challenge
    if (resp := challenger.anti_hcaptcha(ctx)) is None:
> File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 678, in anti_hcaptcha
    if drop := self.tactical_retreat(ctx) in [self.CHALLENGE_BACKCALL]:
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 390, in tactical_retreat
    f"site_link={ctx.current_url} "
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\undetected_chromedriver\__init__.py", line 433, in __getattribute__
    return super().__getattribute__(item)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 527, in current_url
    return self.execute(Command.GET_CURRENT_URL)['value']
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.104)
Stacktrace:
Backtrace:
	(No symbol) [0x009637D3]
	(No symbol) [0x008F8B81]
	(No symbol) [0x007FB36D]
	(No symbol) [0x007DE5DA]
	(No symbol) [0x0084F0CB]
	(No symbol) [0x00860A56]
	(No symbol) [0x0084B216]
	(No symbol) [0x00820D97]
	(No symbol) [0x0082253D]
	GetHandleVerifier [0x00BDABF2+2510930]
	GetHandleVerifier [0x00C08EC1+2700065]
	GetHandleVerifier [0x00C0C86C+2714828]
	GetHandleVerifier [0x00A13480+645344]
	(No symbol) [0x00900FD2]
	(No symbol) [0x00906C68]
	(No symbol) [0x00906D4B]
	(No symbol) [0x00910D6B]
	BaseThreadInitThunk [0x75C000F9+25]
	RtlGetAppContainerNamedObjectPath [0x77167BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77167B8E+238]

2023-02-20 04:38:56.319 | ERROR    | hcaptcha_challenger.core:anti_hcaptcha:699 - Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.104)
Stacktrace:
Backtrace:
	(No symbol) [0x008637D3]
	(No symbol) [0x007F8B81]
	(No symbol) [0x006FB36D]
	(No symbol) [0x006DE5DA]
	(No symbol) [0x0074F0CB]
	(No symbol) [0x00760A56]
	(No symbol) [0x0074B216]
	(No symbol) [0x00720D97]
	(No symbol) [0x0072253D]
	GetHandleVerifier [0x00ADABF2+2510930]
	GetHandleVerifier [0x00B08EC1+2700065]
	GetHandleVerifier [0x00B0C86C+2714828]
	GetHandleVerifier [0x00913480+645344]
	(No symbol) [0x00800FD2]
	(No symbol) [0x00806C68]
	(No symbol) [0x00806D4B]
	(No symbol) [0x00810D6B]
	BaseThreadInitThunk [0x75C000F9+25]
	RtlGetAppContainerNamedObjectPath [0x77167BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77167B8E+238]

Traceback (most recent call last):
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\test.py", line 77, in <module>
    hit_challenge(ctx=driver,challenger=challenger)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\test.py", line 44, in hit_challenge
    if (resp := challenger.anti_hcaptcha(ctx)) is None:
> File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 662, in anti_hcaptcha
    if drop := self.get_label(ctx) in [self.CHALLENGE_BACKCALL]:
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 337, in get_label
    ).until(EC.presence_of_element_located((By.XPATH, "//h2[@class='prompt-text']")))
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 86, in until
    value = method(self._driver)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 69, in _predicate
    return driver.find_element(*locator)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 830, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.104)
Stacktrace:
Backtrace:
	(No symbol) [0x008637D3]
	(No symbol) [0x007F8B81]
	(No symbol) [0x006FB36D]
	(No symbol) [0x006DE5DA]
	(No symbol) [0x0074F0CB]
	(No symbol) [0x00760A56]
	(No symbol) [0x0074B216]
	(No symbol) [0x00720D97]
	(No symbol) [0x0072253D]
	GetHandleVerifier [0x00ADABF2+2510930]
	GetHandleVerifier [0x00B08EC1+2700065]
	GetHandleVerifier [0x00B0C86C+2714828]
	GetHandleVerifier [0x00913480+645344]
	(No symbol) [0x00800FD2]
	(No symbol) [0x00806C68]
	(No symbol) [0x00806D4B]
	(No symbol) [0x00810D6B]
	BaseThreadInitThunk [0x75C000F9+25]
	RtlGetAppContainerNamedObjectPath [0x77167BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77167B8E+238]

2023-02-21 02:34:14.956 | ERROR    | hcaptcha_challenger.core:captcha_screenshot:299 - Message: element click intercepted: Element is not clickable at point (200, -9704)
  (Session info: chrome=110.0.5481.104)
Stacktrace:
Backtrace:
	(No symbol) [0x008637D3]
	(No symbol) [0x007F8B81]
	(No symbol) [0x006FB36D]
	(No symbol) [0x00734E3B]
	(No symbol) [0x007326DB]
	(No symbol) [0x007303A1]
	(No symbol) [0x00731AFE]
	(No symbol) [0x0072ADCB]
	(No symbol) [0x0074B41C]
	(No symbol) [0x00722B96]
	(No symbol) [0x0074B774]
	(No symbol) [0x00761215]
	(No symbol) [0x0074B216]
	(No symbol) [0x00720D97]
	(No symbol) [0x0072253D]
	GetHandleVerifier [0x00ADABF2+2510930]
	GetHandleVerifier [0x00B08EC1+2700065]
	GetHandleVerifier [0x00B0C86C+2714828]
	GetHandleVerifier [0x00913480+645344]
	(No symbol) [0x00800FD2]
	(No symbol) [0x00806C68]
	(No symbol) [0x00806D4B]
	(No symbol) [0x00810D6B]
	BaseThreadInitThunk [0x75C000F9+25]
	RtlGetAppContainerNamedObjectPath [0x77167BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77167B8E+238]

Traceback (most recent call last):
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\demo_selenium.py", line 76, in bytedance
    hit_challenge(ctx=driver,challenger=challenger)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\demo_selenium.py", line 45, in hit_challenge
    if (resp := challenger.anti_hcaptcha(ctx)) is None:
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 678, in anti_hcaptcha
    if drop := self.tactical_retreat(ctx) in [self.CHALLENGE_BACKCALL]:
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 378, in tactical_retreat
    self.path_screenshot = self.captcha_screenshot(challenge_container)
> File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 295, in captcha_screenshot
    ctx.screenshot(_out_path)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webelement.py", line 355, in screenshot
    png = self.screenshot_as_png
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webelement.py", line 334, in screenshot_as_png
    return b64decode(self.screenshot_as_base64.encode("ascii"))
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webelement.py", line 323, in screenshot_as_base64
    return self._execute(Command.ELEMENT_SCREENSHOT)["value"]
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webelement.py", line 403, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element is not clickable at point (200, -9704)
  (Session info: chrome=110.0.5481.104)
Stacktrace:
Backtrace:
	(No symbol) [0x008637D3]
	(No symbol) [0x007F8B81]
	(No symbol) [0x006FB36D]
	(No symbol) [0x00734E3B]
	(No symbol) [0x007326DB]
	(No symbol) [0x007303A1]
	(No symbol) [0x00731AFE]
	(No symbol) [0x0072ADCB]
	(No symbol) [0x0074B41C]
	(No symbol) [0x00722B96]
	(No symbol) [0x0074B774]
	(No symbol) [0x00761215]
	(No symbol) [0x0074B216]
	(No symbol) [0x00720D97]
	(No symbol) [0x0072253D]
	GetHandleVerifier [0x00ADABF2+2510930]
	GetHandleVerifier [0x00B08EC1+2700065]
	GetHandleVerifier [0x00B0C86C+2714828]
	GetHandleVerifier [0x00913480+645344]
	(No symbol) [0x00800FD2]
	(No symbol) [0x00806C68]
	(No symbol) [0x00806D4B]
	(No symbol) [0x00810D6B]
	BaseThreadInitThunk [0x75C000F9+25]
	RtlGetAppContainerNamedObjectPath [0x77167BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77167B8E+238]

2023-02-21 02:34:16.056 | ERROR    | hcaptcha_challenger.core:anti_hcaptcha:699 - Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.104)
Stacktrace:
Backtrace:
	(No symbol) [0x008637D3]
	(No symbol) [0x007F8B81]
	(No symbol) [0x006FB36D]
	(No symbol) [0x006DE5DA]
	(No symbol) [0x0074F0CB]
	(No symbol) [0x00760A56]
	(No symbol) [0x0074B216]
	(No symbol) [0x00720D97]
	(No symbol) [0x0072253D]
	GetHandleVerifier [0x00ADABF2+2510930]
	GetHandleVerifier [0x00B08EC1+2700065]
	GetHandleVerifier [0x00B0C86C+2714828]
	GetHandleVerifier [0x00913480+645344]
	(No symbol) [0x00800FD2]
	(No symbol) [0x00806C68]
	(No symbol) [0x00806D4B]
	(No symbol) [0x00810D6B]
	BaseThreadInitThunk [0x75C000F9+25]
	RtlGetAppContainerNamedObjectPath [0x77167BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77167B8E+238]

Traceback (most recent call last):
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\demo_selenium.py", line 76, in bytedance
    hit_challenge(ctx=driver,challenger=challenger)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\demo_selenium.py", line 45, in hit_challenge
    if (resp := challenger.anti_hcaptcha(ctx)) is None:
> File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 659, in anti_hcaptcha
    self.switch_to_challenge_frame(ctx)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 320, in switch_to_challenge_frame
    WebDriverWait(ctx, 15, ignored_exceptions=(ElementNotVisibleException,)).until(
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 86, in until
    value = method(self._driver)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 279, in _predicate
    driver.switch_to.frame(driver.find_element(*locator))
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 830, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.104)
Stacktrace:
Backtrace:
	(No symbol) [0x008637D3]
	(No symbol) [0x007F8B81]
	(No symbol) [0x006FB36D]
	(No symbol) [0x006DE5DA]
	(No symbol) [0x0074F0CB]
	(No symbol) [0x00760A56]
	(No symbol) [0x0074B216]
	(No symbol) [0x00720D97]
	(No symbol) [0x0072253D]
	GetHandleVerifier [0x00ADABF2+2510930]
	GetHandleVerifier [0x00B08EC1+2700065]
	GetHandleVerifier [0x00B0C86C+2714828]
	GetHandleVerifier [0x00913480+645344]
	(No symbol) [0x00800FD2]
	(No symbol) [0x00806C68]
	(No symbol) [0x00806D4B]
	(No symbol) [0x00810D6B]
	BaseThreadInitThunk [0x75C000F9+25]
	RtlGetAppContainerNamedObjectPath [0x77167BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77167B8E+238]

2023-02-22 08:27:28.598 | ERROR    | hcaptcha_challenger.core:challenge:551 - Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.104)
Stacktrace:
Backtrace:
	(No symbol) [0x00F437D3]
	(No symbol) [0x00ED8B81]
	(No symbol) [0x00DDB36D]
	(No symbol) [0x00DBE5DA]
	(No symbol) [0x00E2F0CB]
	(No symbol) [0x00E40A56]
	(No symbol) [0x00E2B216]
	(No symbol) [0x00E00D97]
	(No symbol) [0x00E0253D]
	GetHandleVerifier [0x011BABF2+2510930]
	GetHandleVerifier [0x011E8EC1+2700065]
	GetHandleVerifier [0x011EC86C+2714828]
	GetHandleVerifier [0x00FF3480+645344]
	(No symbol) [0x00EE0FD2]
	(No symbol) [0x00EE6C68]
	(No symbol) [0x00EE6D4B]
	(No symbol) [0x00EF0D6B]
	BaseThreadInitThunk [0x75C000F9+25]
	RtlGetAppContainerNamedObjectPath [0x77167BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77167B8E+238]

Traceback (most recent call last):
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 83, in _worker
    work_item.run()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\main.py", line 12, in bytedance_async
    result = bytedance(id, password)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\demo_selenium.py", line 79, in bytedance
    hit_challenge(ctx=driver,challenger=challenger)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\demo_selenium.py", line 45, in hit_challenge
    if (resp := challenger.anti_hcaptcha(ctx)) is None:
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 687, in anti_hcaptcha
    self.challenge(ctx, solution)
> File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 545, in challenge
    WebDriverWait(ctx, 15, ignored_exceptions=(ElementClickInterceptedException,)).until(
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 86, in until
    value = method(self._driver)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 334, in _predicate
    target = driver.find_element(*target)  # grab element at locator
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 830, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.104)
Stacktrace:
Backtrace:
	(No symbol) [0x00F437D3]
	(No symbol) [0x00ED8B81]
	(No symbol) [0x00DDB36D]
	(No symbol) [0x00DBE5DA]
	(No symbol) [0x00E2F0CB]
	(No symbol) [0x00E40A56]
	(No symbol) [0x00E2B216]
	(No symbol) [0x00E00D97]
	(No symbol) [0x00E0253D]
	GetHandleVerifier [0x011BABF2+2510930]
	GetHandleVerifier [0x011E8EC1+2700065]
	GetHandleVerifier [0x011EC86C+2714828]
	GetHandleVerifier [0x00FF3480+645344]
	(No symbol) [0x00EE0FD2]
	(No symbol) [0x00EE6C68]
	(No symbol) [0x00EE6D4B]
	(No symbol) [0x00EF0D6B]
	BaseThreadInitThunk [0x75C000F9+25]
	RtlGetAppContainerNamedObjectPath [0x77167BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77167B8E+238]

2023-02-22 08:27:29.688 | ERROR    | hcaptcha_challenger.core:anti_hcaptcha:699 - Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.104)
Stacktrace:
Backtrace:
	(No symbol) [0x00F437D3]
	(No symbol) [0x00ED8B81]
	(No symbol) [0x00DDB36D]
	(No symbol) [0x00DBE5DA]
	(No symbol) [0x00E2F0CB]
	(No symbol) [0x00E40A56]
	(No symbol) [0x00E2B216]
	(No symbol) [0x00E00D97]
	(No symbol) [0x00E0253D]
	GetHandleVerifier [0x011BABF2+2510930]
	GetHandleVerifier [0x011E8EC1+2700065]
	GetHandleVerifier [0x011EC86C+2714828]
	GetHandleVerifier [0x00FF3480+645344]
	(No symbol) [0x00EE0FD2]
	(No symbol) [0x00EE6C68]
	(No symbol) [0x00EE6D4B]
	(No symbol) [0x00EF0D6B]
	BaseThreadInitThunk [0x75C000F9+25]
	RtlGetAppContainerNamedObjectPath [0x77167BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77167B8E+238]

Traceback (most recent call last):
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 83, in _worker
    work_item.run()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\main.py", line 12, in bytedance_async
    result = bytedance(id, password)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\demo_selenium.py", line 79, in bytedance
    hit_challenge(ctx=driver,challenger=challenger)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\demo_selenium.py", line 45, in hit_challenge
    if (resp := challenger.anti_hcaptcha(ctx)) is None:
> File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 690, in anti_hcaptcha
    result, _ = self.challenge_success(ctx)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 598, in challenge_success
    if is_flagged_flow():
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 587, in is_flagged_flow
    WebDriverWait(ctx, 1.2, poll_frequency=0.1).until(
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 86, in until
    value = method(self._driver)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 139, in _predicate
    return _element_if_visible(driver.find_element(*locator))
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 830, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.104)
Stacktrace:
Backtrace:
	(No symbol) [0x00F437D3]
	(No symbol) [0x00ED8B81]
	(No symbol) [0x00DDB36D]
	(No symbol) [0x00DBE5DA]
	(No symbol) [0x00E2F0CB]
	(No symbol) [0x00E40A56]
	(No symbol) [0x00E2B216]
	(No symbol) [0x00E00D97]
	(No symbol) [0x00E0253D]
	GetHandleVerifier [0x011BABF2+2510930]
	GetHandleVerifier [0x011E8EC1+2700065]
	GetHandleVerifier [0x011EC86C+2714828]
	GetHandleVerifier [0x00FF3480+645344]
	(No symbol) [0x00EE0FD2]
	(No symbol) [0x00EE6C68]
	(No symbol) [0x00EE6D4B]
	(No symbol) [0x00EF0D6B]
	BaseThreadInitThunk [0x75C000F9+25]
	RtlGetAppContainerNamedObjectPath [0x77167BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77167B8E+238]

2023-02-22 08:46:21.759 | ERROR    | hcaptcha_challenger.core:anti_hcaptcha:699 - Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.104)
Stacktrace:
Backtrace:
	(No symbol) [0x00F437D3]
	(No symbol) [0x00ED8B81]
	(No symbol) [0x00DDB36D]
	(No symbol) [0x00DBE5DA]
	(No symbol) [0x00E2F0CB]
	(No symbol) [0x00E40A56]
	(No symbol) [0x00E2B216]
	(No symbol) [0x00E00D97]
	(No symbol) [0x00E0253D]
	GetHandleVerifier [0x011BABF2+2510930]
	GetHandleVerifier [0x011E8EC1+2700065]
	GetHandleVerifier [0x011EC86C+2714828]
	GetHandleVerifier [0x00FF3480+645344]
	(No symbol) [0x00EE0FD2]
	(No symbol) [0x00EE6C68]
	(No symbol) [0x00EE6D4B]
	(No symbol) [0x00EF0D6B]
	BaseThreadInitThunk [0x75C000F9+25]
	RtlGetAppContainerNamedObjectPath [0x77167BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77167B8E+238]

Traceback (most recent call last):
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 83, in _worker
    work_item.run()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\main.py", line 12, in bytedance_async
    result = bytedance(id, password)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\demo_selenium.py", line 79, in bytedance
    hit_challenge(ctx=driver,challenger=challenger)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\demo_selenium.py", line 45, in hit_challenge
    if (resp := challenger.anti_hcaptcha(ctx)) is None:
> File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 662, in anti_hcaptcha
    if drop := self.get_label(ctx) in [self.CHALLENGE_BACKCALL]:
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 337, in get_label
    ).until(EC.presence_of_element_located((By.XPATH, "//h2[@class='prompt-text']")))
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 86, in until
    value = method(self._driver)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 69, in _predicate
    return driver.find_element(*locator)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 830, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.104)
Stacktrace:
Backtrace:
	(No symbol) [0x00F437D3]
	(No symbol) [0x00ED8B81]
	(No symbol) [0x00DDB36D]
	(No symbol) [0x00DBE5DA]
	(No symbol) [0x00E2F0CB]
	(No symbol) [0x00E40A56]
	(No symbol) [0x00E2B216]
	(No symbol) [0x00E00D97]
	(No symbol) [0x00E0253D]
	GetHandleVerifier [0x011BABF2+2510930]
	GetHandleVerifier [0x011E8EC1+2700065]
	GetHandleVerifier [0x011EC86C+2714828]
	GetHandleVerifier [0x00FF3480+645344]
	(No symbol) [0x00EE0FD2]
	(No symbol) [0x00EE6C68]
	(No symbol) [0x00EE6D4B]
	(No symbol) [0x00EF0D6B]
	BaseThreadInitThunk [0x75C000F9+25]
	RtlGetAppContainerNamedObjectPath [0x77167BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77167B8E+238]

2023-02-22 08:56:54.946 | ERROR    | hcaptcha_challenger.core:challenge:551 - Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.104)
Stacktrace:
Backtrace:
	(No symbol) [0x00F437D3]
	(No symbol) [0x00ED8B81]
	(No symbol) [0x00DDB36D]
	(No symbol) [0x00DBE5DA]
	(No symbol) [0x00E2F0CB]
	(No symbol) [0x00E40A56]
	(No symbol) [0x00E2B216]
	(No symbol) [0x00E00D97]
	(No symbol) [0x00E0253D]
	GetHandleVerifier [0x011BABF2+2510930]
	GetHandleVerifier [0x011E8EC1+2700065]
	GetHandleVerifier [0x011EC86C+2714828]
	GetHandleVerifier [0x00FF3480+645344]
	(No symbol) [0x00EE0FD2]
	(No symbol) [0x00EE6C68]
	(No symbol) [0x00EE6D4B]
	(No symbol) [0x00EF0D6B]
	BaseThreadInitThunk [0x75C000F9+25]
	RtlGetAppContainerNamedObjectPath [0x77167BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77167B8E+238]

Traceback (most recent call last):
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 83, in _worker
    work_item.run()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\main.py", line 12, in bytedance_async
    result = bytedance(id, password)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\demo_selenium.py", line 79, in bytedance
    hit_challenge(ctx=driver,challenger=challenger)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\demo_selenium.py", line 45, in hit_challenge
    if (resp := challenger.anti_hcaptcha(ctx)) is None:
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 687, in anti_hcaptcha
    self.challenge(ctx, solution)
> File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 545, in challenge
    WebDriverWait(ctx, 15, ignored_exceptions=(ElementClickInterceptedException,)).until(
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 86, in until
    value = method(self._driver)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 334, in _predicate
    target = driver.find_element(*target)  # grab element at locator
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 830, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.104)
Stacktrace:
Backtrace:
	(No symbol) [0x00F437D3]
	(No symbol) [0x00ED8B81]
	(No symbol) [0x00DDB36D]
	(No symbol) [0x00DBE5DA]
	(No symbol) [0x00E2F0CB]
	(No symbol) [0x00E40A56]
	(No symbol) [0x00E2B216]
	(No symbol) [0x00E00D97]
	(No symbol) [0x00E0253D]
	GetHandleVerifier [0x011BABF2+2510930]
	GetHandleVerifier [0x011E8EC1+2700065]
	GetHandleVerifier [0x011EC86C+2714828]
	GetHandleVerifier [0x00FF3480+645344]
	(No symbol) [0x00EE0FD2]
	(No symbol) [0x00EE6C68]
	(No symbol) [0x00EE6D4B]
	(No symbol) [0x00EF0D6B]
	BaseThreadInitThunk [0x75C000F9+25]
	RtlGetAppContainerNamedObjectPath [0x77167BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77167B8E+238]

2023-02-22 08:56:56.054 | ERROR    | hcaptcha_challenger.core:anti_hcaptcha:699 - Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.104)
Stacktrace:
Backtrace:
	(No symbol) [0x00F437D3]
	(No symbol) [0x00ED8B81]
	(No symbol) [0x00DDB36D]
	(No symbol) [0x00DBE5DA]
	(No symbol) [0x00E2F0CB]
	(No symbol) [0x00E40A56]
	(No symbol) [0x00E2B216]
	(No symbol) [0x00E00D97]
	(No symbol) [0x00E0253D]
	GetHandleVerifier [0x011BABF2+2510930]
	GetHandleVerifier [0x011E8EC1+2700065]
	GetHandleVerifier [0x011EC86C+2714828]
	GetHandleVerifier [0x00FF3480+645344]
	(No symbol) [0x00EE0FD2]
	(No symbol) [0x00EE6C68]
	(No symbol) [0x00EE6D4B]
	(No symbol) [0x00EF0D6B]
	BaseThreadInitThunk [0x75C000F9+25]
	RtlGetAppContainerNamedObjectPath [0x77167BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77167B8E+238]

Traceback (most recent call last):
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 83, in _worker
    work_item.run()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\main.py", line 12, in bytedance_async
    result = bytedance(id, password)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\demo_selenium.py", line 79, in bytedance
    hit_challenge(ctx=driver,challenger=challenger)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\demo_selenium.py", line 45, in hit_challenge
    if (resp := challenger.anti_hcaptcha(ctx)) is None:
> File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 690, in anti_hcaptcha
    result, _ = self.challenge_success(ctx)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 598, in challenge_success
    if is_flagged_flow():
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 587, in is_flagged_flow
    WebDriverWait(ctx, 1.2, poll_frequency=0.1).until(
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 86, in until
    value = method(self._driver)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 139, in _predicate
    return _element_if_visible(driver.find_element(*locator))
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 830, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.104)
Stacktrace:
Backtrace:
	(No symbol) [0x00F437D3]
	(No symbol) [0x00ED8B81]
	(No symbol) [0x00DDB36D]
	(No symbol) [0x00DBE5DA]
	(No symbol) [0x00E2F0CB]
	(No symbol) [0x00E40A56]
	(No symbol) [0x00E2B216]
	(No symbol) [0x00E00D97]
	(No symbol) [0x00E0253D]
	GetHandleVerifier [0x011BABF2+2510930]
	GetHandleVerifier [0x011E8EC1+2700065]
	GetHandleVerifier [0x011EC86C+2714828]
	GetHandleVerifier [0x00FF3480+645344]
	(No symbol) [0x00EE0FD2]
	(No symbol) [0x00EE6C68]
	(No symbol) [0x00EE6D4B]
	(No symbol) [0x00EF0D6B]
	BaseThreadInitThunk [0x75C000F9+25]
	RtlGetAppContainerNamedObjectPath [0x77167BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77167B8E+238]

2023-02-22 09:10:34.417 | ERROR    | hcaptcha_challenger.core:anti_hcaptcha:699 - Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.104)
Stacktrace:
Backtrace:
	(No symbol) [0x00F437D3]
	(No symbol) [0x00ED8B81]
	(No symbol) [0x00DDB36D]
	(No symbol) [0x00DBE5DA]
	(No symbol) [0x00E2F0CB]
	(No symbol) [0x00E40A56]
	(No symbol) [0x00E2B216]
	(No symbol) [0x00E00D97]
	(No symbol) [0x00E0253D]
	GetHandleVerifier [0x011BABF2+2510930]
	GetHandleVerifier [0x011E8EC1+2700065]
	GetHandleVerifier [0x011EC86C+2714828]
	GetHandleVerifier [0x00FF3480+645344]
	(No symbol) [0x00EE0FD2]
	(No symbol) [0x00EE6C68]
	(No symbol) [0x00EE6D4B]
	(No symbol) [0x00EF0D6B]
	BaseThreadInitThunk [0x75C000F9+25]
	RtlGetAppContainerNamedObjectPath [0x77167BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77167B8E+238]

Traceback (most recent call last):
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 83, in _worker
    work_item.run()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\main.py", line 12, in bytedance_async
    result = bytedance(id, password)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\demo_selenium.py", line 79, in bytedance
    hit_challenge(ctx=driver,challenger=challenger)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\papara\flask\demo_selenium.py", line 45, in hit_challenge
    if (resp := challenger.anti_hcaptcha(ctx)) is None:
> File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 667, in anti_hcaptcha
    if drop := self.mark_samples(ctx) in [
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 432, in mark_samples
    samples = ctx.find_elements(By.XPATH, "//div[@class='task-image']")
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 860, in find_elements
    return self.execute(Command.FIND_ELEMENTS, {"using": by, "value": value})["value"] or []
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.104)
Stacktrace:
Backtrace:
	(No symbol) [0x00F437D3]
	(No symbol) [0x00ED8B81]
	(No symbol) [0x00DDB36D]
	(No symbol) [0x00DBE5DA]
	(No symbol) [0x00E2F0CB]
	(No symbol) [0x00E40A56]
	(No symbol) [0x00E2B216]
	(No symbol) [0x00E00D97]
	(No symbol) [0x00E0253D]
	GetHandleVerifier [0x011BABF2+2510930]
	GetHandleVerifier [0x011E8EC1+2700065]
	GetHandleVerifier [0x011EC86C+2714828]
	GetHandleVerifier [0x00FF3480+645344]
	(No symbol) [0x00EE0FD2]
	(No symbol) [0x00EE6C68]
	(No symbol) [0x00EE6D4B]
	(No symbol) [0x00EF0D6B]
	BaseThreadInitThunk [0x75C000F9+25]
	RtlGetAppContainerNamedObjectPath [0x77167BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77167B8E+238]

2023-03-03 04:56:31.503 | ERROR    | hcaptcha_challenger.core:tactical_retreat:382 - Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.178)
Stacktrace:
Backtrace:
	(No symbol) [0x010637D3]
	(No symbol) [0x00FF8B81]
	(No symbol) [0x00EFB36D]
	(No symbol) [0x00EDE5DA]
	(No symbol) [0x00F4F0CB]
	(No symbol) [0x00F60A56]
	(No symbol) [0x00F4B216]
	(No symbol) [0x00F20D97]
	(No symbol) [0x00F2253D]
	GetHandleVerifier [0x012DABF2+2510930]
	GetHandleVerifier [0x01308EC1+2700065]
	GetHandleVerifier [0x0130C86C+2714828]
	GetHandleVerifier [0x01113480+645344]
	(No symbol) [0x01000FD2]
	(No symbol) [0x01006C68]
	(No symbol) [0x01006D4B]
	(No symbol) [0x01010D6B]
	BaseThreadInitThunk [0x75C000F9+25]
	RtlGetAppContainerNamedObjectPath [0x77167BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77167B8E+238]

Traceback (most recent call last):
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 83, in _worker
    work_item.run()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\FlaskApp\app.py", line 12, in bytedance_async
    result = bytedance(id, password)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\FlaskApp\demo_selenium.py", line 82, in bytedance
    hit_challenge(ctx=driver,challenger=challenger)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\FlaskApp\demo_selenium.py", line 39, in hit_challenge
    if (resp := challenger.anti_hcaptcha(ctx)) is None:
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 678, in anti_hcaptcha
    if drop := self.tactical_retreat(ctx) in [self.CHALLENGE_BACKCALL]:
> File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 377, in tactical_retreat
    challenge_container = ctx.find_element(By.XPATH, "//body[@class='no-selection']")
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 830, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.178)
Stacktrace:
Backtrace:
	(No symbol) [0x010637D3]
	(No symbol) [0x00FF8B81]
	(No symbol) [0x00EFB36D]
	(No symbol) [0x00EDE5DA]
	(No symbol) [0x00F4F0CB]
	(No symbol) [0x00F60A56]
	(No symbol) [0x00F4B216]
	(No symbol) [0x00F20D97]
	(No symbol) [0x00F2253D]
	GetHandleVerifier [0x012DABF2+2510930]
	GetHandleVerifier [0x01308EC1+2700065]
	GetHandleVerifier [0x0130C86C+2714828]
	GetHandleVerifier [0x01113480+645344]
	(No symbol) [0x01000FD2]
	(No symbol) [0x01006C68]
	(No symbol) [0x01006D4B]
	(No symbol) [0x01010D6B]
	BaseThreadInitThunk [0x75C000F9+25]
	RtlGetAppContainerNamedObjectPath [0x77167BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77167B8E+238]

2023-03-03 04:56:31.574 | ERROR    | hcaptcha_challenger.core:anti_hcaptcha:699 - Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.178)
Stacktrace:
Backtrace:
	(No symbol) [0x010637D3]
	(No symbol) [0x00FF8B81]
	(No symbol) [0x00EFB36D]
	(No symbol) [0x00EDE5DA]
	(No symbol) [0x00F4F0CB]
	(No symbol) [0x00F60A56]
	(No symbol) [0x00F4B216]
	(No symbol) [0x00F20D97]
	(No symbol) [0x00F2253D]
	GetHandleVerifier [0x012DABF2+2510930]
	GetHandleVerifier [0x01308EC1+2700065]
	GetHandleVerifier [0x0130C86C+2714828]
	GetHandleVerifier [0x01113480+645344]
	(No symbol) [0x01000FD2]
	(No symbol) [0x01006C68]
	(No symbol) [0x01006D4B]
	(No symbol) [0x01010D6B]
	BaseThreadInitThunk [0x75C000F9+25]
	RtlGetAppContainerNamedObjectPath [0x77167BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77167B8E+238]

Traceback (most recent call last):
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 83, in _worker
    work_item.run()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\FlaskApp\app.py", line 12, in bytedance_async
    result = bytedance(id, password)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\FlaskApp\demo_selenium.py", line 82, in bytedance
    hit_challenge(ctx=driver,challenger=challenger)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\FlaskApp\demo_selenium.py", line 39, in hit_challenge
    if (resp := challenger.anti_hcaptcha(ctx)) is None:
> File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 678, in anti_hcaptcha
    if drop := self.tactical_retreat(ctx) in [self.CHALLENGE_BACKCALL]:
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 390, in tactical_retreat
    f"site_link={ctx.current_url} "
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\seleniumbase\undetected\__init__.py", line 314, in __getattribute__
    return super().__getattribute__(item)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 530, in current_url
    return self.execute(Command.GET_CURRENT_URL)["value"]
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.178)
Stacktrace:
Backtrace:
	(No symbol) [0x010637D3]
	(No symbol) [0x00FF8B81]
	(No symbol) [0x00EFB36D]
	(No symbol) [0x00EDE5DA]
	(No symbol) [0x00F4F0CB]
	(No symbol) [0x00F60A56]
	(No symbol) [0x00F4B216]
	(No symbol) [0x00F20D97]
	(No symbol) [0x00F2253D]
	GetHandleVerifier [0x012DABF2+2510930]
	GetHandleVerifier [0x01308EC1+2700065]
	GetHandleVerifier [0x0130C86C+2714828]
	GetHandleVerifier [0x01113480+645344]
	(No symbol) [0x01000FD2]
	(No symbol) [0x01006C68]
	(No symbol) [0x01006D4B]
	(No symbol) [0x01010D6B]
	BaseThreadInitThunk [0x75C000F9+25]
	RtlGetAppContainerNamedObjectPath [0x77167BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77167B8E+238]

2023-03-03 05:16:54.120 | ERROR    | hcaptcha_challenger.core:anti_hcaptcha:699 - Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.178)
Stacktrace:
Backtrace:
	(No symbol) [0x010637D3]
	(No symbol) [0x00FF8B81]
	(No symbol) [0x00EFB36D]
	(No symbol) [0x00EDE5DA]
	(No symbol) [0x00F4F0CB]
	(No symbol) [0x00F60A56]
	(No symbol) [0x00F4B216]
	(No symbol) [0x00F20D97]
	(No symbol) [0x00F2253D]
	GetHandleVerifier [0x012DABF2+2510930]
	GetHandleVerifier [0x01308EC1+2700065]
	GetHandleVerifier [0x0130C86C+2714828]
	GetHandleVerifier [0x01113480+645344]
	(No symbol) [0x01000FD2]
	(No symbol) [0x01006C68]
	(No symbol) [0x01006D4B]
	(No symbol) [0x01010D6B]
	BaseThreadInitThunk [0x75C000F9+25]
	RtlGetAppContainerNamedObjectPath [0x77167BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77167B8E+238]

Traceback (most recent call last):
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 83, in _worker
    work_item.run()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\FlaskApp\app.py", line 12, in bytedance_async
    result = bytedance(id, password)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\FlaskApp\demo_selenium.py", line 83, in bytedance
    hit_challenge(ctx=driver,challenger=challenger)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\FlaskApp\demo_selenium.py", line 39, in hit_challenge
    if (resp := challenger.anti_hcaptcha(ctx)) is None:
> File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 667, in anti_hcaptcha
    if drop := self.mark_samples(ctx) in [
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 434, in mark_samples
    alias = sample.get_attribute("aria-label")
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webelement.py", line 177, in get_attribute
    attribute_value = self.parent.execute_script(
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 500, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.178)
Stacktrace:
Backtrace:
	(No symbol) [0x010637D3]
	(No symbol) [0x00FF8B81]
	(No symbol) [0x00EFB36D]
	(No symbol) [0x00EDE5DA]
	(No symbol) [0x00F4F0CB]
	(No symbol) [0x00F60A56]
	(No symbol) [0x00F4B216]
	(No symbol) [0x00F20D97]
	(No symbol) [0x00F2253D]
	GetHandleVerifier [0x012DABF2+2510930]
	GetHandleVerifier [0x01308EC1+2700065]
	GetHandleVerifier [0x0130C86C+2714828]
	GetHandleVerifier [0x01113480+645344]
	(No symbol) [0x01000FD2]
	(No symbol) [0x01006C68]
	(No symbol) [0x01006D4B]
	(No symbol) [0x01010D6B]
	BaseThreadInitThunk [0x75C000F9+25]
	RtlGetAppContainerNamedObjectPath [0x77167BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77167B8E+238]

2023-03-03 05:26:54.477 | ERROR    | hcaptcha_challenger.core:anti_hcaptcha:699 - Message: 
Stacktrace:
Backtrace:
	(No symbol) [0x010637D3]
	(No symbol) [0x00FF8B81]
	(No symbol) [0x00EFB36D]
	(No symbol) [0x00F2D382]
	(No symbol) [0x00F2D4BB]
	(No symbol) [0x00F63302]
	(No symbol) [0x00F4B464]
	(No symbol) [0x00F61215]
	(No symbol) [0x00F4B216]
	(No symbol) [0x00F20D97]
	(No symbol) [0x00F2253D]
	GetHandleVerifier [0x012DABF2+2510930]
	GetHandleVerifier [0x01308EC1+2700065]
	GetHandleVerifier [0x0130C86C+2714828]
	GetHandleVerifier [0x01113480+645344]
	(No symbol) [0x01000FD2]
	(No symbol) [0x01006C68]
	(No symbol) [0x01006D4B]
	(No symbol) [0x01010D6B]
	BaseThreadInitThunk [0x75C000F9+25]
	RtlGetAppContainerNamedObjectPath [0x77167BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77167B8E+238]

Traceback (most recent call last):
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 83, in _worker
    work_item.run()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\FlaskApp\app.py", line 12, in bytedance_async
    result = bytedance(id, password)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\FlaskApp\demo_selenium.py", line 87, in bytedance
    hit_challenge(ctx=driver,challenger=challenger)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\FlaskApp\demo_selenium.py", line 39, in hit_challenge
    if (resp := challenger.anti_hcaptcha(ctx)) is None:
> File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 659, in anti_hcaptcha
    self.switch_to_challenge_frame(ctx)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 320, in switch_to_challenge_frame
    WebDriverWait(ctx, 15, ignored_exceptions=(ElementNotVisibleException,)).until(
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
Backtrace:
	(No symbol) [0x010637D3]
	(No symbol) [0x00FF8B81]
	(No symbol) [0x00EFB36D]
	(No symbol) [0x00F2D382]
	(No symbol) [0x00F2D4BB]
	(No symbol) [0x00F63302]
	(No symbol) [0x00F4B464]
	(No symbol) [0x00F61215]
	(No symbol) [0x00F4B216]
	(No symbol) [0x00F20D97]
	(No symbol) [0x00F2253D]
	GetHandleVerifier [0x012DABF2+2510930]
	GetHandleVerifier [0x01308EC1+2700065]
	GetHandleVerifier [0x0130C86C+2714828]
	GetHandleVerifier [0x01113480+645344]
	(No symbol) [0x01000FD2]
	(No symbol) [0x01006C68]
	(No symbol) [0x01006D4B]
	(No symbol) [0x01010D6B]
	BaseThreadInitThunk [0x75C000F9+25]
	RtlGetAppContainerNamedObjectPath [0x77167BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77167B8E+238]

2023-03-03 05:36:01.255 | ERROR    | hcaptcha_challenger.core:anti_hcaptcha:699 - Message: 
Stacktrace:
Backtrace:
	(No symbol) [0x010637D3]
	(No symbol) [0x00FF8B81]
	(No symbol) [0x00EFB36D]
	(No symbol) [0x00F2D382]
	(No symbol) [0x00F2D4BB]
	(No symbol) [0x00F63302]
	(No symbol) [0x00F4B464]
	(No symbol) [0x00F61215]
	(No symbol) [0x00F4B216]
	(No symbol) [0x00F20D97]
	(No symbol) [0x00F2253D]
	GetHandleVerifier [0x012DABF2+2510930]
	GetHandleVerifier [0x01308EC1+2700065]
	GetHandleVerifier [0x0130C86C+2714828]
	GetHandleVerifier [0x01113480+645344]
	(No symbol) [0x01000FD2]
	(No symbol) [0x01006C68]
	(No symbol) [0x01006D4B]
	(No symbol) [0x01010D6B]
	BaseThreadInitThunk [0x75C000F9+25]
	RtlGetAppContainerNamedObjectPath [0x77167BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77167B8E+238]

Traceback (most recent call last):
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 83, in _worker
    work_item.run()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\FlaskApp\app.py", line 12, in bytedance_async
    result = bytedance(id, password)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\FlaskApp\demo_selenium.py", line 87, in bytedance
    hit_challenge(ctx=driver,challenger=challenger)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\FlaskApp\demo_selenium.py", line 39, in hit_challenge
    if (resp := challenger.anti_hcaptcha(ctx)) is None:
> File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 659, in anti_hcaptcha
    self.switch_to_challenge_frame(ctx)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 320, in switch_to_challenge_frame
    WebDriverWait(ctx, 15, ignored_exceptions=(ElementNotVisibleException,)).until(
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
Backtrace:
	(No symbol) [0x010637D3]
	(No symbol) [0x00FF8B81]
	(No symbol) [0x00EFB36D]
	(No symbol) [0x00F2D382]
	(No symbol) [0x00F2D4BB]
	(No symbol) [0x00F63302]
	(No symbol) [0x00F4B464]
	(No symbol) [0x00F61215]
	(No symbol) [0x00F4B216]
	(No symbol) [0x00F20D97]
	(No symbol) [0x00F2253D]
	GetHandleVerifier [0x012DABF2+2510930]
	GetHandleVerifier [0x01308EC1+2700065]
	GetHandleVerifier [0x0130C86C+2714828]
	GetHandleVerifier [0x01113480+645344]
	(No symbol) [0x01000FD2]
	(No symbol) [0x01006C68]
	(No symbol) [0x01006D4B]
	(No symbol) [0x01010D6B]
	BaseThreadInitThunk [0x75C000F9+25]
	RtlGetAppContainerNamedObjectPath [0x77167BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77167B8E+238]

2023-03-03 05:37:13.048 | ERROR    | hcaptcha_challenger.core:anti_hcaptcha:699 - Message: 
Stacktrace:
Backtrace:
	(No symbol) [0x010637D3]
	(No symbol) [0x00FF8B81]
	(No symbol) [0x00EFB36D]
	(No symbol) [0x00F2D382]
	(No symbol) [0x00F2D4BB]
	(No symbol) [0x00F63302]
	(No symbol) [0x00F4B464]
	(No symbol) [0x00F61215]
	(No symbol) [0x00F4B216]
	(No symbol) [0x00F20D97]
	(No symbol) [0x00F2253D]
	GetHandleVerifier [0x012DABF2+2510930]
	GetHandleVerifier [0x01308EC1+2700065]
	GetHandleVerifier [0x0130C86C+2714828]
	GetHandleVerifier [0x01113480+645344]
	(No symbol) [0x01000FD2]
	(No symbol) [0x01006C68]
	(No symbol) [0x01006D4B]
	(No symbol) [0x01010D6B]
	BaseThreadInitThunk [0x75C000F9+25]
	RtlGetAppContainerNamedObjectPath [0x77167BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77167B8E+238]

Traceback (most recent call last):
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 83, in _worker
    work_item.run()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\FlaskApp\app.py", line 12, in bytedance_async
    result = bytedance(id, password)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\FlaskApp\demo_selenium.py", line 87, in bytedance
    hit_challenge(ctx=driver,challenger=challenger)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\FlaskApp\demo_selenium.py", line 39, in hit_challenge
    if (resp := challenger.anti_hcaptcha(ctx)) is None:
> File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 659, in anti_hcaptcha
    self.switch_to_challenge_frame(ctx)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 320, in switch_to_challenge_frame
    WebDriverWait(ctx, 15, ignored_exceptions=(ElementNotVisibleException,)).until(
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
Backtrace:
	(No symbol) [0x010637D3]
	(No symbol) [0x00FF8B81]
	(No symbol) [0x00EFB36D]
	(No symbol) [0x00F2D382]
	(No symbol) [0x00F2D4BB]
	(No symbol) [0x00F63302]
	(No symbol) [0x00F4B464]
	(No symbol) [0x00F61215]
	(No symbol) [0x00F4B216]
	(No symbol) [0x00F20D97]
	(No symbol) [0x00F2253D]
	GetHandleVerifier [0x012DABF2+2510930]
	GetHandleVerifier [0x01308EC1+2700065]
	GetHandleVerifier [0x0130C86C+2714828]
	GetHandleVerifier [0x01113480+645344]
	(No symbol) [0x01000FD2]
	(No symbol) [0x01006C68]
	(No symbol) [0x01006D4B]
	(No symbol) [0x01010D6B]
	BaseThreadInitThunk [0x75C000F9+25]
	RtlGetAppContainerNamedObjectPath [0x77167BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77167B8E+238]

2023-03-03 05:40:18.960 | ERROR    | hcaptcha_challenger.core:anti_hcaptcha:699 - Message: 
Stacktrace:
Backtrace:
	(No symbol) [0x010637D3]
	(No symbol) [0x00FF8B81]
	(No symbol) [0x00EFB36D]
	(No symbol) [0x00F2D382]
	(No symbol) [0x00F2D4BB]
	(No symbol) [0x00F63302]
	(No symbol) [0x00F4B464]
	(No symbol) [0x00F61215]
	(No symbol) [0x00F4B216]
	(No symbol) [0x00F20D97]
	(No symbol) [0x00F2253D]
	GetHandleVerifier [0x012DABF2+2510930]
	GetHandleVerifier [0x01308EC1+2700065]
	GetHandleVerifier [0x0130C86C+2714828]
	GetHandleVerifier [0x01113480+645344]
	(No symbol) [0x01000FD2]
	(No symbol) [0x01006C68]
	(No symbol) [0x01006D4B]
	(No symbol) [0x01010D6B]
	BaseThreadInitThunk [0x75C000F9+25]
	RtlGetAppContainerNamedObjectPath [0x77167BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77167B8E+238]

Traceback (most recent call last):
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 83, in _worker
    work_item.run()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\FlaskApp\app.py", line 12, in bytedance_async
    result = bytedance(id, password)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\FlaskApp\demo_selenium.py", line 85, in bytedance
    hit_challenge(ctx=driver,challenger=challenger)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\FlaskApp\demo_selenium.py", line 39, in hit_challenge
    if (resp := challenger.anti_hcaptcha(ctx)) is None:
> File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 659, in anti_hcaptcha
    self.switch_to_challenge_frame(ctx)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 320, in switch_to_challenge_frame
    WebDriverWait(ctx, 15, ignored_exceptions=(ElementNotVisibleException,)).until(
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
Backtrace:
	(No symbol) [0x010637D3]
	(No symbol) [0x00FF8B81]
	(No symbol) [0x00EFB36D]
	(No symbol) [0x00F2D382]
	(No symbol) [0x00F2D4BB]
	(No symbol) [0x00F63302]
	(No symbol) [0x00F4B464]
	(No symbol) [0x00F61215]
	(No symbol) [0x00F4B216]
	(No symbol) [0x00F20D97]
	(No symbol) [0x00F2253D]
	GetHandleVerifier [0x012DABF2+2510930]
	GetHandleVerifier [0x01308EC1+2700065]
	GetHandleVerifier [0x0130C86C+2714828]
	GetHandleVerifier [0x01113480+645344]
	(No symbol) [0x01000FD2]
	(No symbol) [0x01006C68]
	(No symbol) [0x01006D4B]
	(No symbol) [0x01010D6B]
	BaseThreadInitThunk [0x75C000F9+25]
	RtlGetAppContainerNamedObjectPath [0x77167BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77167B8E+238]

2023-03-03 05:42:58.286 | ERROR    | hcaptcha_challenger.core:anti_hcaptcha:699 - Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.178)
Stacktrace:
Backtrace:
	(No symbol) [0x010637D3]
	(No symbol) [0x00FF8B81]
	(No symbol) [0x00EFB36D]
	(No symbol) [0x00EDE5DA]
	(No symbol) [0x00F4F0CB]
	(No symbol) [0x00F60A56]
	(No symbol) [0x00F4B216]
	(No symbol) [0x00F20D97]
	(No symbol) [0x00F2253D]
	GetHandleVerifier [0x012DABF2+2510930]
	GetHandleVerifier [0x01308EC1+2700065]
	GetHandleVerifier [0x0130C86C+2714828]
	GetHandleVerifier [0x01113480+645344]
	(No symbol) [0x01000FD2]
	(No symbol) [0x01006C68]
	(No symbol) [0x01006D4B]
	(No symbol) [0x01010D6B]
	BaseThreadInitThunk [0x75C000F9+25]
	RtlGetAppContainerNamedObjectPath [0x77167BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77167B8E+238]

Traceback (most recent call last):
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 83, in _worker
    work_item.run()
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\FlaskApp\app.py", line 12, in bytedance_async
    result = bytedance(id, password)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\FlaskApp\demo_selenium.py", line 85, in bytedance
    hit_challenge(ctx=driver,challenger=challenger)
  File "C:\Users\izzet\OneDrive\Belgeler\MEGAsync Downloads\FlaskApp\demo_selenium.py", line 39, in hit_challenge
    if (resp := challenger.anti_hcaptcha(ctx)) is None:
> File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 659, in anti_hcaptcha
    self.switch_to_challenge_frame(ctx)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\hcaptcha_challenger\core.py", line 320, in switch_to_challenge_frame
    WebDriverWait(ctx, 15, ignored_exceptions=(ElementNotVisibleException,)).until(
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 86, in until
    value = method(self._driver)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 279, in _predicate
    driver.switch_to.frame(driver.find_element(*locator))
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 830, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\izzet\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.178)
Stacktrace:
Backtrace:
	(No symbol) [0x010637D3]
	(No symbol) [0x00FF8B81]
	(No symbol) [0x00EFB36D]
	(No symbol) [0x00EDE5DA]
	(No symbol) [0x00F4F0CB]
	(No symbol) [0x00F60A56]
	(No symbol) [0x00F4B216]
	(No symbol) [0x00F20D97]
	(No symbol) [0x00F2253D]
	GetHandleVerifier [0x012DABF2+2510930]
	GetHandleVerifier [0x01308EC1+2700065]
	GetHandleVerifier [0x0130C86C+2714828]
	GetHandleVerifier [0x01113480+645344]
	(No symbol) [0x01000FD2]
	(No symbol) [0x01006C68]
	(No symbol) [0x01006D4B]
	(No symbol) [0x01010D6B]
	BaseThreadInitThunk [0x75C000F9+25]
	RtlGetAppContainerNamedObjectPath [0x77167BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77167B8E+238]

